Repository Terralego/TerraVisu, pull requests merged in 2023-06, with the labels that each got.

#235 Add token & user session infos in frontend settings
  project/visu/api.py
  project/visu/tests/test_api.py
Labels: enhancement

#236 Provide SSO login and logout urls in API settings
  docs/source/changelog.rst
  project/visu/api.py
  project/visu/tests/test_api.py
Labels: enhancement

#248 Set SSO login button internal / external text in config
  docs/source/changelog.rst
  project/settings/__init__.py
  project/visu/api.py
  project/visu/tests/test_api.py
Labels: enhancement

#250 Bump requests to 2.31.0
  dev-requirements.txt
  requirements.txt
Labels: dependencies, python

#251 Bump sqlparse to 0.4.4
  dev-requirements.txt
  requirements.txt
Labels: dependencies, python

#253 Customize info menu content in config dashboard
  docs/source/changelog.rst
  project/settings/__init__.py
  project/urls.py
  project/visu/api.py
  project/visu/tests/test_api.py
  requirements.in
  requirements.txt
Labels: enhancement, Frontend, backend

#249 Fix absolute url background styles
  project/terra_layer/serializers.py
  project/terra_layer/views/layers.py
Labels: Bug

#255 Use build cache docker
  .github/workflows/release.yml
Labels: github_actions

#265 Add Pie charts management
  docs/source/changelog.rst
  project/terra_layer/migrations/0012_layer_advanced_style.py
  project/terra_layer/models.py
  project/terra_layer/sources_serializers.py
  project/terra_layer/tests/test_commands/test_layer_dump.py
  project/terra_layer/tests/test_views.py
  project/terra_layer/views/layers.py
Labels: enhancement

#267 Improve info content editor
  docs/source/changelog.rst
  project/VERSION
  project/settings/__init__.py
Labels: enhancement, backend

#271 Fix API source permission
  docs/source/changelog.rst
  project/VERSION
  project/geosource/permissions.py
  project/geosource/tests/test_api.py
Labels: Bug
