Repository Terralego/TerraVisu, pull requests merged in 2024-02, with the labels that each got.

#536 Improve Dashboard / Config Interface
  .github/workflows/test.yml
  Makefile
  docs/source/others/changelog.rst
  project/VERSION
  project/accounts/apps.py
  project/accounts/migrations/0005_alter_user_options.py
  project/accounts/models.py
  project/fixtures/initial.json
  project/geosource/admin.py
  project/geosource/migrations/0012_alter_commandsource_options_alter_csvsource_options_and_more.py
  project/geosource/models.py
  project/locales/en/LC_MESSAGES/django.po
  project/locales/fr/LC_MESSAGES/django.po
  project/settings/__init__.py
  project/terra_layer/admin.py
  project/urls.py
  requirements.in
  requirements.txt
Labels: enhancement

#538 New debug panel
  conf/nginx.dev.conf
  docs/source/others/changelog.rst
  install/conf/nginx.conf
  project/VERSION
  project/accounts/admin.py
  project/admin.py
  project/fixtures/initial.json
  project/locales/en/LC_MESSAGES/django.po
  project/locales/fr/LC_MESSAGES/django.po
  project/settings/__init__.py
  project/templates/admin/base.html
  project/terra_layer/tests/test_admin.py
  project/urls.py
  project/visu/admin.py
Labels: enhancement

#534 [Documentation] Add configuration dashboard doc
  docs/source/_static/images/django/config.png
  docs/source/_static/images/django/config2.png
  docs/source/index.rst
  docs/source/others/changelog.rst
  docs/source/user_manual/admin_user_guide.rst
  docs/source/user_manual/module_configuration.rst
Labels: documentation

#560 Update doc about report and status
  docs/source/_static/images/admin/admin_couche_liste.png
  docs/source/_static/images/admin/admin_source_creation_postgis.png
  docs/source/_static/images/admin/admin_source_infosgenerales.png
  docs/source/_static/images/admin/admin_source_listesource.png
  docs/source/_static/images/admin/admin_source_listesource_status.png
  docs/source/_static/images/admin/admin_source_rapportimportation_alert.png
  docs/source/_static/images/admin/admin_sources.png
  docs/source/_static/images/admin/statut_encours.png
  docs/source/_static/images/admin/statut_termine.png
  docs/source/user_manual/admin_user_guide.rst
Labels: documentation, enhancement

#570 [Documentation] Update visuals for user guide and fix typos
  docs/source/_static/images/visu/visu_filtre.png
  docs/source/_static/images/visu/visu_filtre_arbrecouches.gif
  docs/source/_static/images/visu/visu_filtre_arbrecouches.png
  docs/source/_static/images/visu/visu_interfacecarto.png
  docs/source/_static/images/visu/visu_interfacecarto_couche.png
  docs/source/_static/images/visu/visu_legende.png
  docs/source/_static/images/visu/visu_outilnavigation.png
  docs/source/_static/images/visu/visu_partage.png
  docs/source/_static/images/visu/visu_recherche.png
  docs/source/_static/images/visu/visu_transparence.png
  docs/source/_static/images/visu/visu_widget.png
  docs/source/_static/images/visu/vue.png
  docs/source/user_manual/admin_user_guide.rst
  docs/source/user_manual/user_guide.rst
Labels: documentation
